x-base-image:
  versions:
    moc: &moc 0.6.4 
  name: &base_name "local/base"

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        MOC_VERSION: *moc
    image: *base_name
  wasm:
    build:
      context: .
      args:
        IMAGE: *base_name
    volumes:
      - ./out:/project/out
    environment:
      compress : no
    command: bash --login build.sh
